name: Publish components
on:
  push:
    branches: main
    paths:
      - "components/**.tsx"
      - ".github/workflows/components.yaml"
      - "webpack.config.js"

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.DEPLOY_AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.DEPLOY_AWS_ACCESS_SECRET }}
  AWS_DEFAULT_REGION: us-east-1

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: install
        run: npm install --force
      - name: build
        run: npm run build:components
      - name: Upload
        run: aws s3 sync build s3://roamjs.com/static-site
