name: Publish components
on:
  push:
    branches: main
    paths:
      - "components/**.tsx"
      - ".github/workflows/components.yaml"
      - "webpack.config.js"

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.DEPLOY_AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.DEPLOY_AWS_ACCESS_SECRET }}
  AWS_DEFAULT_REGION: us-east-1

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.14.0
        uses: actions/setup-node@v1
        with:
          node-version: 16.14.0
      - name: install
        run: npm install
      - name: build
        run: npm run build:components
      - name: Upload
        run: aws s3 sync build s3://roamjs.com/static-site
      - name: Invalidate Cache
        run: |
          CLOUDFRONT_ID=$(aws cloudfront list-distributions --query "DistributionList.Items[*].{Alias:Aliases.Items[0],Id:Id}[?Alias=='roamjs.com'].Id" --output text)
          aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_ID --paths "/static-site/*"
