name: Push to Main
on:
  push:
    branches: main
    paths:
      - "lambdas/**"
      - ".github/workflows/lambdas.yaml"
      - "package.json"

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.DEPLOY_AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.DEPLOY_AWS_ACCESS_SECRET }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.16.1
        uses: actions/setup-node@v1
        with:
          node-version: 12.16.1
      - name: install
        run: npm install
      - name: Setup env
        run: |
          echo "SUPPORT_ROAM_PASSWORD=${{ secrets.SUPPORT_ROAM_PASSWORD }}" > .env.local
          echo "AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID" >> .env.local
          echo "AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY" >> .env.local
          echo "CLOUDFRONT_SECRET=${{ secrets.CLOUDFRONT_SECRET }}" >> .env.local
          echo "CLOUDFORMATION_ROLE_ARN=${{ secrets.CLOUDFORMATION_ROLE_ARN }}" >> .env.local
          echo "ORIGIN_LAMBDA_ARN=${{ secrets.ORIGIN_LAMBDA_ARN }}" >> .env.local
          echo "CLOUDWATCH_ROLE_ARN=${{ secrets.CLOUDWATCH_ROLE_ARN }}" >> .env.local
          echo "DEPLOY_LAMBDA_ARN=${{ secrets.DEPLOY_LAMBDA_ARN }}" >> .env.local
          echo "SNS_TOPIC_ARN=${{ secrets.SNS_TOPIC_ARN }}" >> .env.local
          echo "S3_WEBSITE_ENDPOINT=${{ secrets.S3_WEBSITE_ENDPOINT }}" >> .env.local
          echo "ROAMJS_ZONE_ID=${{ secrets.ROAMJS_ZONE_ID }}" >> .env.local
      - name: Deploy
        run: npm run lambdas
