name: Publish Extension
on:
  push:
    branches: main
    paths:
      - "package.json"
      - "src/**"
      - ".github/workflows/main.yaml"

env:
  API_URL: https://lambda.roamjs.com
  DEPLOY_ENDPOINT: deploy-website

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install
        run: npm install
      - name: build
        run: npm run build 
      - name: RoamJS Publish
        uses: dvargas92495/roamjs-publish@0.4.2
        with:
          token: ${{ secrets.ROAMJS_DEVELOPER_TOKEN }}
          source: build
          path: static-site
          release_token: ${{ secrets.ROAMJS_RELEASE_TOKEN }}
          email: dvargas92495@gmail.com
