name: Push to Main
on:
  push:
    branches: main
    paths:
      - "src/*"
      - "webpack.config.js"
      - ".github/workflows/main.yaml"

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.DEPLOY_AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.DEPLOY_AWS_ACCESS_SECRET }}
  AWS_DEFAULT_REGION: us-east-1

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.16.1
        uses: actions/setup-node@v1
        with:
          node-version: 12.16.1
      - name: install
        run: npm install
      - name: Setup env
        run: |
          echo "VERCEL_TOKEN=${{ secrets.VERCEL_TOKEN }}" > .env.local
          echo "AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID" >> .env.local
          echo "AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY" >> .env.local
      - name: Build
        run: npm run build
      - name: Deploy
        run: npm run deploy
