name: Publish Extension
on:
  push:
    branches: main
    paths:
      - "package.json"
      - "src/**"
      - ".github/workflows/main.yaml"

env:
  API_URL: https://lambda.roamjs.com
  ROAMJS_DEVELOPER_TOKEN: ${{ secrets.ROAMJS_DEVELOPER_TOKEN }}
  ROAMJS_EMAIL: support@roamjs.com
  ROAMJS_EXTENSION_ID: static-site
  # GITHUB_TOKEN: ${{ secrets.ROAMJS_RELEASE_TOKEN }} - no need for releases and roam depot pushes for now
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ vars.AWS_REGION }}
  ROAMJS_PROXY: ${{ vars.ROAMJS_PROXY }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install
        run: npm install --force
      - name: build
        run: npx samepage build
